### ISSUE TITLE
Offset joints

### ISSUE THREAD

**Issue by Jungduri** [Mathux/TMR#10]
Hi,

I have a quick question.
I am wondering why offset joints are needed when you compute guoh3dfeats?

Code lines are in src/guofeats/motion_representation/_get_joints_to_guofeats

Thank you

**Comment by Mathux** [comment]
Hello, 

This code has been taken from this repo https://github.com/EricGuo5513/HumanML3D/blob/main/motion_representation.ipynb
I suggest to ask this to the original authors. 

I had to include this representation in order to be compatible with prior work.
Best
