### ISSUE TITLE
Pretrained model for hand and body

### ISSUE THREAD

**Issue by vadeli** [Mathux/TMR#12]
Hi. Thanks for the great work. I was wondering if there is any pretrained model for TMR that supports both hand and body.

**Comment by Mathux** [comment]
Hi @vadeli,

TMR does not support hand (or face) motions. We could still use TMR on these motions by "cutting" the hands.

It may be possible to train such model but the only issue is data. Most data in AMASS doesn't really contains face or hand motions. Also, the text annotations of HumanML3D are done with skeleton visualisations (without hands or faces). 
I think we can train TMR if such dataset exists. 

Best
