### ISSUE TITLE
Motion Rendering

### ISSUE THREAD

**Issue by JHang2020** [Mathux/TMR#14]
Hello, thanks for the great work.
I'd like to ask how to render the 3D human motion like that reported in your paper instead of the only skeleton but the mesh version?

**Comment by mesnico** [comment]
@Mathux I am also interested in rendering 3D motions. I was able to follow the instructions in the TEMOS repository to obtain the nice 3D visualizations.
However, they suppose .npy files are produced using jointtype=vertices from the `sample.py` script.

In the retrieval case, motions are the original ones (they are not generated). Therefore, I imagine there should exist a script that converts .npy files within the `pose_data` directory into a renderable .npy format.

Is such conversion script available? If not, which are the steps required to achieve this?

Thank you in advance

**Comment by Mathux** [comment]
Hello @JHang2020, 

As @mesnico suggested, you can use the code provided in TEMOS: https://github.com/Mathux/TEMOS

It is indeed true that the motions are not generated (it is text-to-motion retrieval). You should load the files into the `pose_data` directory, they are in the SMPL format representation. You should load the poses, betas and trans fields, pass these two the SMPL layer, to get the vertices. You can then save them as npy for the rendering script.
