### ISSUE TITLE
looking forward to TMR++

### ISSUE THREAD

**Issue by GuangtaoLyu** [Mathux/TMR#15]
thank you for your great work.
looking forward to TMR++.

**Comment by Mathux** [comment]
Hi @GuangtaoLyu,

The code of TMR++ is available at this address: https://github.com/leorebensabath/TMRPlusPlus
Please contact Léore if you have any questions.

**Comment by GuangtaoLyu** [comment]
> Hi @GuangtaoLyu,
> 
> The code of TMR++ is available at this address: https://github.com/leorebensabath/TMRPlusPlus Please contact Léore if you have any questions.

Can you share the script for action recognition?
thank you.
