### ISSUE TITLE
Paper Question 

### ISSUE THREAD

**Issue by ChangeNext** [Mathux/TMR#19]
Thank you for the amazing project.

In Figure3 of the paper, you say “ we provide sample qualitative results for text-to-motion retrieval on the full test set of H3D.” You say 
If Rank1 000000.npy and Rank2 M000000.npy, do you mean Rank1 for both together?

I'm asking because you said you used the full test set, but the retrieved motion doesn't have symmetrical motion.

**Comment by Mathux** [comment]
Hi @ChangeNext, 

Thanks for your interest in TMR. 

In fact, you're right, we omitted the mirror version so as not to confuse the reader in the figure. We should have made this clear in the legend. However, the mirror versions are included in the appendix.

Best
