### ISSUE TITLE
The motion encoder and its representation

### ISSUE THREAD

**Issue by ChenFengYe** [Mathux/TMR#2]
Hi, Mathux. Thanks for your impressive work on motion retrieval. It could support many works in this field. I was wondering if you could provide more about your release plan (like the motion encoder) and the motion representation. Is it similar to the one used in HumanML3D?

In addition, I was wondering if TMR could be used to evaluate motion generation. Specifically, could its motion scores be used like R-Precision or even to assess motion quality? I have some doubts about the accuracy of the motion encoder provided by the HumanML3D dataset, and I believe that TMR may be a more reliable tool for this purpose.

Thank you for your time and expertise!

**Comment by Evm7** [comment]
Hi! I am also interested in the motion encoder part. Is there any news on when this code will by released?

**Comment by kingchurch** [comment]
Hi, Mathux, will you release the training code sometime ? It will be very helpful to see if we can train a new evaluation model for T2M with this approach.

**Comment by Mathux** [comment]
Hello all,

Yes the training code, and evaluation models will be released in the near future (at the ICCV conference at the latest).
