### ISSUE TITLE
eval with threshold

### ISSUE THREAD

**Issue by yinkangning0124** [Mathux/TMR#7]
Hi @Mathux :
    when running the evaluation with threshold of my own model, I faced the problems below and I wonder how to fix this issue?
    In my setting, the shape of sims and text_selfsim is all (512, 512), and I set the threhold to 0.8.
Thanks a lot !
![image](https://github.com/Mathux/TMR/assets/45726315/693ed45a-61af-438b-b998-89abb9f46e06)

**Comment by Mathux** [comment]
Hello @yinkangning0124,

Thanks for your interest with TMR. 

Do you have the same issue when evaluating with the provided pre-trained model?
If you don't get the issue, can you check if the shape of the tensors are similar between the two models? (``dists``, ``idx`` , ``partition``)

For debugging, you can try to split the line into two lines:
```python
dd = dists[tuple(idx.T)]
gt_dists = np.minimum.reduceat(dd, partition)
```

**Comment by yinkangning0124** [comment]
Yeah, I solved the issue, the type of text_selfsim should be nparray instead of tensor.
Thanks again for your great work !
