### ISSUE TITLE
python encode_dataset.py error

### ISSUE THREAD

**Issue by ahgdwang** [Mathux/TMR#9]
python encode_dataset.py run_dir=/data/home/wangyiming/Motion/TMR/models/tmr_humanml3d_guoh3dfeats

Error executing job with overrides: ['run_dir=/data/home/wangyiming/Motion/TMR/models/tmr_humanml3d_guoh3dfeats']
Error in call to target 'src.data.text_motion.TextMotionDataset':
FileNotFoundError(2, 'No such file or directory')

**Comment by Mathux** [comment]
Hello @ahgdwang,

Can you add ``HYDRA_FULL_ERROR=1`` before your command? This will make debugging easier. 
It seems that there is a problem during data loading.
